export const ERROR_CODES = {
  VALIDATION_ERROR: "E001",
  NOT_FOUND: "E002",
  DATABASE_FAILURE: "E003",
  INTERNAL_ERROR: "E500",
  AUTHENTICATION_ERROR: "E401",
  AUTHORIZATION_ERROR: "E403",
  CONFLICT_ERROR: "E409",
  RATE_LIMIT_ERROR: "E429",
  NETWORK_ERROR: "E503",
  TIMEOUT_ERROR: "E504",
};
